/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_header/jni.h"
/* Header for class top_dreamlike_VirtualThreadUnsafe */

#ifndef _Included_top_dreamlike_VirtualThreadUnsafe
#define _Included_top_dreamlike_VirtualThreadUnsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_dreamlike_VirtualThreadUnsafe
 * Method:    getTrustedLookUp
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_top_dreamlike_VirtualThreadUnsafe_getTrustedLookUp
        (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_top_dreamlike_VirtualThreadUnsafe_getMainA(JNIEnv *env, jclass jclazz);

#ifdef __cplusplus
}
#endif
#endif
